image: fedora:rawhide

variables:
  DEPENDENCIES: gcc
                gtk-doc
                pkgconfig(udev)
                pkgconfig(systemd)
                pkgconfig(gio-2.0)
                pkgconfig(gudev-1.0)
                systemd
                gtk3-devel
                meson
                git
                python3-gobject
                python3-dbusmock
                python3-psutil
                umockdev

build_stable:
  before_script:
    - dnf upgrade -y --nogpgcheck fedora-release fedora-repos*
    - dnf update -y && dnf install -y $DEPENDENCIES
  script:
    - meson -Dgtk_doc=true -Dgtk-tests=true _build
    - ninja -v -C _build
    - ninja -v -C _build install
    - ninja -v -C _build uninstall
    - ninja -v -C _build dist
    - meson test -C _build
  artifacts:
    when: on_failure
    name: "iio-sensor-proxy-${CI_COMMIT_REF_NAME}"
    paths:
      - "${CI_PROJECT_DIR}/_build/meson-logs"
